### ISSUE TITLE
Fully track response status from kernel

### ISSUE THREAD

**Issue by lrasmus** [StatTag/JupyterKernelManager#1]
Implement full tracking of the status messages that are returned by a kernel per the [Messaging protocol](https://jupyter-client.readthedocs.io/en/stable/messaging.html).  Right now the library is optimistically assuming all messages succeed.

**Comment by jasongrout** [comment]
Be careful that though the spec says that all reply messages must have a status field, in actuality some kernels omit the status field on things like kernel_info_reply messages. We need to eventually have better message compliance testing for kernels, but in the meantime in JupyterLab, we assume that a missing status field on kernel_info_reply messages are an okay status.

**Comment by lrasmus** [comment]
That's really good to know, thank you so much @jasongrout !
